config/routes.rb
App7::Application.routes.draw do
  resources :line_item1s

  resources :carts

  resources :line_items

  get "store/index"
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
   
    resources :users do
    collection do
    get :forgot_password   #the account-email submisison form url
    post :reset_password  #a url for the function that sends the response email
  end
end
  controller :users do
    get 'forgot_password' => :forgot_password
 
  end
  
  resources :users

  resources :products

   match 'users/forgot_password' => 'users#forgot_password'

  root :to => 'store#index', :as => 'store'

end

app/models/user.rb
class User < ActiveRecord::Base
 attr_accessible :password_confirmation, :name, :password , :email_id, :roles
  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  validate :password_must_be_present
    class << self
      def authenticate(name, password)
          if user = find_by_name(name)
          if user.hashed_password == encrypt_password(password, user.salt)
          user
          end
      end
    end
    def encrypt_password(password, salt)
      Digest::SHA2.hexdigest(password + "wibble" + salt)
      end
    end
# 'password' is a virtual attribute
    def password=(password)
    @password = password
      if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
      end
    end
    private
    def password_must_be_present
      errors.add(:password, "Missing password" ) unless hashed_password.present?
    end
    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
   skip_before_filter :authorize , :only => [:new,:create,:forgot_password,:reset_password]
  def index
    # @users = User.all
     @users = User.order(:name)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    #@users = User.find(params[:id])
    @user=User.find_by_id( session[:user_id])
     @user.save
      respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    p 111111111111
    p params
    p 222222222222
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, :notice => 'User #{@user.name} was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  def forgot_password
   
 end
 def reset_password
   p 777777777777777777777777777777777777777777777777777777
   p params
   p params[:user]
   email_id=params[:user][:email]
  p username=params[:user][:text]
  #a=Random.rand(10..100)
  # puts (rand() * 1000).to_i
   code = (rand() * 1000).to_i
   p code
   @code =code
   @user=User.find_by_name(username)
   #p 111111111111111111111111111111111111111111111111111
   p @user
    p @user.name
    p @user.email_id
    p email_id
   #P  111111111111111111111111111111111111111111111111111
   if(@user.name)
     if(@user.email_id==email_id)
         Notifier.forgot_password(@emai_id,code).deliver
      end
      respond_to do |format|
      format.html { redirect_to edit_user_url(@user.id) }
      format.json { head :no_content }
    end 
  end 
 
  
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <fieldset>
      <legend>Enter User Details</legend>
      <div>
        <%= f.label :name %>:
          <%= f.text_field :name, :size => 40 %>
          </div>
      <div>
        <%= f.label :password, 'Password' %>:
        <%= f.password_field :password, :size => 40 %>
      </div>
      <div>
        <%= f.label :password_confirmation, 'Confirm' %>:
        <%= f.password_field :password_confirmation, :size => 40 %>
        </div>
      <div>
      <div>
        <%= f.label :email_id %>:
        <%= f.text_field :email_id, :size => 40 %>
        </div>
      <div>
        <%= f.submit %>
      </div>
    </fieldset>
  <% end %>
  
 
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', store_index_path %>

app/views/users/forgot_password.html.erb
 <h3>forgot  Password</h3>
		<%= form_for(:user, :url => reset_password_users_path) do |f| %>
				<p>Enter the email address you used to register for this site.</p></br>
				<div class="field">
				<%=f.label :username%>
				<%=f.text_field:text%></br  ></br>
				<%= f.label :email %>  
				<%= f.text_field :email %> 
			</div>
		<div class="actions">
		<%= f.submit "Send Email" %>
		</div> 
<% end %>

app/views/users/forgotpassword.html.erb
 
				<p>Enter the email address you used to register for this site.</p></br>
				<div class="field">
				<%= f.label :email %>  </br>
				<%= f.text_field :email %> 
			</div>
			<div class="actions">
			<%= f.submit "Send Email" %>
			</div> 

app/views/users/index.html.erb
<h1>Listing users</h1>
	<% if notice %>
		<p id="notice"><%= notice %></p>
	<% end %>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

<%= button_to 'Logout', logout_path, :method => :delete %>
<%=link_to 'Logout',logout_path, :method =>:delete%>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>


<%= link_to 'Back', login_path %>

app/views/users/reset_password.html.erb
 <h3>forgot  Password</h3>
		<%#= form_for(:user, :url => reset_password_users_path) do |f| %>
				<p>Enter the email address you used to register for this site.</p></br>
				<div class="field">
				<%= f.label :token %>  </br>
				<%= f.text_field :text_field%> 
			</div>
		<div class="actions">
		<%= f.submit "Send Email" %>
		</div> 
<% end %>

app/views/users/show.html.erb
<% if notice %>
		<p id="notice"><%= notice %></p>
	<% end %>
<p>
   <table>
      <tr>
        <th>name</th>
        <th>email_id</th>
 
      </tr>
      <tr>
        <td>
          <%= @user.name %>
        </td>
        <td>
          <%=@user.email_id%>
        </td>
       </tr>
    </table>
</p>
  


<%= link_to 'Edit', edit_user_path(@user) %> 
<%#= link_to 'Back', users_path %>
<%= link_to 'Back', store_index_path %>